// IMAGE SETTINGS
fadeAlpha = .3; // THE OPACITY OF THE PLATFORM WHEN FADED

// FADE TIMING
timer = 0;
waitTimeToFade = 120; // WHEN SOLID, THE PLATFORM WILL WAIT THIS LONG BEFORE FADING
fadeTime = 120; // WHEN FADED, THIS IS HOW LONG THE PLATFORM WILL REMAIN FADED


// DO NOT TOUCH BELOW
ethereal = false; 